### ISSUE TITLE
Host-Client version mismatch

### ISSUE THREAD

**Issue by kombolasha** [cezanne/usbip-win#219]
Hi, 
First of all, thank you for all your hard work here; it is very much appreciated!

I followed these steps exactly, and I believe I've installed the VHCI driver correctly; it's in my device manager and looks OK, but when I try to attach a device in PowerShell, I get... 
"usbip: error: open vhci driver
usbip: error: read_devbuf: failed to read: err: 0x6"

Despite the error, the command lights up the LED on the flash drive I'm trying to reach, so I know it's doing something; it just doesn't show the flash drive in "This PC". 
The server returns this...
"usbipd: info: received request: 0x8003(5)
usbipd: info: found requested device: 1-1.2
usbip: info: connect: 1-1.2
usbipd: debug: usbipd.c:164:[recv_request_import] import request busid 1-1.2: complete"

The usbip version on my Raspberry Pi is (usbip-utils 2.0), but on the Windows 10 client, it's (usbip 1.0.0). Would that be why I'm receiving the error? If so, how do I get them to match?
Thanks!

**Comment by cezanne** [comment]
@kombolasha : Even though usbip-win version string does not match with "usbip-utils 2.0", it is no problem. That versioned linux binaries are working good with usbip-win. 
Your error( 0x6 ) in the client means that a server closed the connection. And it's natural that the usbipd did not have error messages. Because usbipd handed over to your kernel module in raspberry Pi. There should be some releated errors in kernel log. Please share the logs.

**Comment by kombolasha** [comment]
@cezanne Thanks for the prompt response! I’ll try to upload the log as soon as I get past some other issues that have cropped up.

**Comment by kombolasha** [comment]
After a bunch of trial and error, multiple BSOD events when trying to uninstall the driver, and eventually a fresh OS install, I got it to work once and never again. I'm a noob and the kernel log was even more complicated than the process itself, so I gave up and I'm now using Virtualhere, which worked great for my application.
I do want to thank you for your willingness to help and keeping usbip alive for those adept enough to figure it out!
