### ISSUE TITLE
Windows 7(x86 platform) support

### ISSUE THREAD

**Issue by Zero3K** [cezanne/usbip-win#91]
How do I do that?

**Comment by Zero3K** [comment]
Maybe you all could make a wiki that includes how to do that.

**Comment by MegaZeroX10** [comment]
I was able to get it built for a x64 platform of Windows 7 but not for a x86 platform of it. Please check https://github.com/cezanne/usbip-win/issues/95 for more info.

**Comment by cezanne** [comment]
@MegaZeroX10 : Well, indeed, x86 platform is in a low priority. But @cantops in an old issue(#17) reported successful deployment in x86.

**Comment by MegaZeroX10** [comment]
I don't know how he managed to get it compiled.

**Comment by cezanne** [comment]
@MegaZeroX10 : I just uploaded a new branch to build usbip-win against x86 platform. Please check [build_x86 branch](https://github.com/cezanne/usbip-win/tree/build_x86). I confirmed compilation but have not tested because there's no x86 machine. Can you check ? I attached x86 binaries( [usbip-win-x86.zip](https://github.com/cezanne/usbip-win/files/4329597/usbip-win-x86.zip) )

**Comment by Dimazhan** [comment]
An error occurs while installing the vhci driver:

> The driver for this device could not be loaded. The driver may be corrupted or missing. (Code 39)

Stub driver installed without errors, after editing architecture in inf file

**Comment by cezanne** [comment]
@Dimazhan : Thanks for your response. Well, it is fortunate that the stub works. :cry: 

x86 support is not a major concern. I'll just merge x86 build patch into the master branch.
